#!/usr/bin/env ruby

require 'popcorntime_search'
require 'highline/import'
require 'optparse'

options = {}

optparse = OptionParser.new do |opts|
  opts.banner = 'Usage: popcorn [options] <search>'

  opts.on('-y', '--auto', 'Pick best match automatically') do
    options[:auto] = true
  end

  opts.on('-v', '--version', 'Print version and exit') do
    puts "popcorn v#{PopcorntimeSearch::VERSION}"
    exit
  end

  opts.on('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end.parse!

# Join arguments to create the search term
options[:search] = optparse.join(' ')

begin
  HighLine.colorize_strings

  if options[:search].empty?
    puts opts
    exit
  end

  search = PopcorntimeSearch::Search.new(options[:search])

  unless search.results_found?
    say 'No results found'.red
    exit
  end

  # If there are several matches, choose the appropriate one
  say "Search results for #{options[:search].blue}:".yellow
  result = choose(*search.results) do |menu|
    menu.default = '1'
    menu.select_by = :index_or_name
  end

  say result
rescue Interrupt, EOFError
  say 'Interrupted!'.red
rescue SocketError
  say "Couldn't perform action. Are you online?".red
end
